### ISSUE TITLE
2.0 exe got flagged by antivirus

### ISSUE THREAD

**Issue by Locke20041** [SutandoTsukai181/RyuModManager#10]
So I downloaded the new .exe and it and the .asi got flagged by Norton. Now I know Norton is kind of shit but still, a flag's a flag.
Just a consideration.
![fuck you norton](https://user-images.githubusercontent.com/107245196/173021959-480a64c2-b00d-4012-902a-e3924b025d7d.png)

**Comment by mosamadeeb** [comment]
Googling the "Threat name" shows that it is an [indicator that a new version of a file has not been used a lot yet](https://knowledge.broadcom.com/external/article/191764/endpoint-protection-detects-known-good-a.html). You can even see it in the "Very Few Users" comment below the threat name.

Anyway, [this is the only difference](https://github.com/SutandoTsukai181/YakuzaParless/commit/a5de417e10448ad3382c99b2c9594e19ca87a9f2) between the YakuzaParless.asi from this version, and the one from the previous release (RMM v1.7).

Feel free to compile from source if you're still worried.
