### ISSUE TITLE
Yakuza 6 wont start

### ISSUE THREAD

**Issue by Asunix666** [SutandoTsukai181/RyuModManager#13]
Tried with patches and without and same rezult. It just hangs in task manager with 20mb. Can't try with older versions since you delete them.

**Comment by mosamadeeb** [comment]
You need to give more context. Which version of the game are you using, how did you install RMM, what does your game folder look like after installing it, etc.

There are no functional differences between latest version and RMM versions before 2.0. You can still use the CLI mode by running RMM from the command line with the `--cli` argument.

**Comment by Asunix666** [comment]
Upd20210607. Ryu Mod Manager v2.1 not cli. files in game; mods, RyuModManager.exe, YakuzaParless.asi, YakuzaParless.ini. YakuzaParless.mlo is generated only in cmd but game still no load. Same rezult with no mods. Never got this issue with other Yakuza games. Getting game version not supported error(even though  other games still worked). Can you give me a version that was made where there wherent any patches?

**Comment by mosamadeeb** [comment]
You still didn't give enough context. Please go to the modding discord for help.
https://discord.gg/yakuzamodding

**Comment by Asunix666** [comment]
I beg you! Give me a archive with older versions. I've tried to compile source code in visual studio, but i get errors and warnings since i never used that program. I'm not a programmer, and i don't want to. Thanks!

**Comment by mosamadeeb** [comment]
The old releases were removed for a reason, and they're not coming back. There is no functional differences between 1.7 and 2.0. As I said, go to the modding discord and ask for help there. GitHub issues are for reporting bugs anyway, not for tech support.
