### ISSUE TITLE
Ryu doesn't even make it start up

### ISSUE THREAD

**Issue by HouseOfKhonjin** [SutandoTsukai181/RyuModManager#14]
I installed a few mods on Nexus, but whenever I try to start up Yakuza 0, It doesn't even start up no matter how I try. anyone know the solution?

**Comment by KaylinOwO** [comment]
I believe Yakuza 0 is just broken with the latest version of RMM as I have the same issue with the latest, use 3.0 instead for now https://www.nexusmods.com/yakuza0/mods/524?tab=files&file_id=1891

**Comment by mosamadeeb** [comment]
This issue was fixed by [this commit](https://github.com/SutandoTsukai181/YakuzaParless/commit/9b84b933a028a1ddb756e5f53196e34b1082a6c1), and the fix is now present in RMM v3.2.
