### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by Suruuuu** [SutandoTsukai181/RyuModManager#2]
I added mods, it says that they're added and all that, but when I open the game, the mods are nowhere to be seen, any help? 
![image](https://user-images.githubusercontent.com/86446513/123343290-c50d9100-d551-11eb-8d22-85ea534f90d6.png)

**Comment by mosamadeeb** [comment]
The issue tracker is for reporting bugs/suggesting features.

For support with using the tool, please go to the #modding-help channel in the Yakuza Modding Community server.

https://discord.gg/Fke3NmZRW5
