### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by higuyspppp** [SutandoTsukai181/RyuModManager#3]
I'm pretty new at modding.  But every time I load up the game I always get this error  called "Assertion Failed."  With an expression: "countMatches." Any solution?

**Comment by Ryo-ch** [comment]
> I'm pretty new at modding. But every time I load up the game I always get this error called "Assertion Failed." With an expression: "countMatches." Any solution?

Perhaps you should buy the game beforehand 💖

**Comment by higuyspppp** [comment]
Eh, never mind.  I was able to fix the issue on my own, and no I did not pirate the game or get it on game pass.

**Comment by That1Weeabo** [comment]
> Eh, never mind. I was able to fix the issue on my own, and no I did not pirate the game or get it on game pass.

Hey, can ya tell me how were you able to fix this issue?

**Comment by higuyspppp** [comment]
Yeah, sorry for the late response.  But my fix does not work anymore. I suggest you take SutandoTsukai’s advice and just get the game on steam…
