### ISSUE TITLE
Errors in the source code

### ISSUE THREAD

**Issue by 000Daniel** [SutandoTsukai181/RyuModManager#6]
Hey in ModLoadOrder.cs line 40
I get this error:
> Argument 1: cannot convert from 'System.IO.FileStream' to 'Yarhl.IO.DataStream' [ModLoadOrder]

also in the same file (line 93 for example) and in other files I get this error:
> Argument 2: cannot convert from 'System.IO.SeekOrigin' to 'Yarhl.IO.SeekMode' [ModLoadOrder]

how can I fix these errors?

I have all the libraries working I believe...

**Comment by mosamadeeb** [comment]
Did you fetch the submodules through git after cloning? It's stated in the building guide in the readme.
If it still doesn't work, then you should try updating the dependencies manually for each project in Visual Studio.
