### ISSUE TITLE
Problem with parless.asi

### ISSUE THREAD

**Issue by ramapratamad** [SutandoTsukai181/RyuModManager#7]
Hey I appreciate your mod manager so much, I think it's helpful but I have this problem that bothering me.
When I open up Yakuza0.exe with ryu mod manager installed (already follow all instructions right) it show an error "microsoft c++ assertion failed, parless.asi line 22 etc" - I've tried several  methods like uninstall all vcredist and install it again, I'm a newbie and thank you!

**Comment by XinaTheThird** [comment]
same problem here, win10 version support is a hit or miss you'll have to replace the files manually

**Comment by ZeltraX007** [comment]
same

**Comment by mosamadeeb** [comment]
The Windows 10 (UWP/GamePass) version of the game is currently unsupported.
If you're getting the `assertion failed` error and you're not using the GamePass version, then your game is not updated to the latest Steam version.
