### ISSUE TITLE
No "mods folders"

### ISSUE THREAD

**Issue by TheMayor77** [SutandoTsukai181/RyuModManager#8]
I was trying to install a moveset mod for Kiwami 2 and the Installing Mods instructions say to move it to the "mods" folder in the game's directory but no such folder seems to exist. Also, when I run the Mod Manager, only two of the new files show up, as the other "mods" folder is absent. This is my first time modding, can anyone help explain what I might be doing wrong?

**Comment by mosamadeeb** [comment]
Check the console output for RyuModManager. You should have seen this in the console output:
`Aborting: No supported game was found in this directory`

The `/mods/` folder is not created automatically if the directory does not contain a valid game (you installed RMM in the wrong directory).
